### ISSUE TITLE
Searching for 'constructor' crashes

### ISSUE THREAD

**Issue by tony-scio** [joshjung/trie-search#39]
Here's a test case that crashes:

```diff
diff --git a/test/trie-search.test.js b/test/trie-search.test.js
index 0f21f68..5cbd2ef 100644
--- a/test/trie-search.test.js
+++ b/test/trie-search.test.js
@@ -82,6 +82,10 @@ describe('TrieSearch', function() {
       assert.equal(ts.get('blab').length, 0);
       assert.equal(ts.get('nope').length, 0);
     });
+
+    it('get(\'constructor\') should work', function() {
+      assert.equal(ts.get('constructor').length, 0);
+    });
   });
 
   describe('TrieSearch::addAll(...)should work for an array', function() {
```

The stack is:
```
    TypeError: Cannot read properties of undefined (reading 'length')
    
          331 |         accumulator = reducer(accumulator, phrases[i], matches, this);
          332 |       } else {
        > 333 |         ret = ret ? ret.addAll(matches) : new HashArray(haKeyFields).addAll(matches);
              |                                                                      ^
          334 |       }
          335 |     }
          336 |
    
          at JClass.addAll (node_modules/hasharray/src/HashArray.js:70:13)
          at TrieSearch.get (src/TrieSearch.js:333:70)
          at Object.<anonymous> (test/trie-search.test.js:88:23)
```

**Comment by tony-scio** [comment]
@joshjung I put up a fix here: https://github.com/joshjung/hash-array/pull/4
