### ISSUE TITLE
"constructor" doesn't work as a key

### ISSUE THREAD

**Issue by glin** [joshjung/trie-search#6]
### Reproducible example
```js
const TrieSearch = require("trie-search")

const trie = new TrieSearch();
trie.addFromObject({ constructor: 1 });
trie.get('c');
```

### Output
```
TypeError: this._map[inst].indexOf is not a function
    at JClass.addOne (/tmp/node_modules/hasharray/src/HashArray.js:44:31)
    at JClass.add (/tmp/node_modules/hasharray/src/HashArray.js:60:12)
    at JClass.addAll (/tmp/node_modules/hasharray/src/HashArray.js:71:16)
    at aggregate (/tmp/node_modules/trie-search/src/TrieSearch.js:202:12)
    at aggregate (/tmp/node_modules/trie-search/src/TrieSearch.js:206:11)
    at aggregate (/tmp/node_modules/trie-search/src/TrieSearch.js:206:11)
    at aggregate (/tmp/node_modules/trie-search/src/TrieSearch.js:206:11)
    at aggregate (/tmp/node_modules/trie-search/src/TrieSearch.js:206:11)
    at aggregate (/tmp/node_modules/trie-search/src/TrieSearch.js:206:11)
    at aggregate (/tmp/node_modules/trie-search/src/TrieSearch.js:206:11)
```

**Comment by joshjung** [comment]
Hey @glin I haven't had a chance to really look deeply into this yet. However, the problem is probably related to the fact that `constructor` has some special cases that are treated differently than other fields:

https://stackoverflow.com/questions/21320256/is-there-a-way-to-make-constructor-a-valid-key-in-a-js-object

I might get a chance during my next pass at optimizations to take a look at this specific issue, but it's low priority right now. If you would like to create a PR on `trie-search` or `hasharray` to fix this, feel free!
